name: Docker Image CI

on:
  push:
    branches:
    - main
    - release/*
    tags:
      - v*
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build --no-cache
